# -*- coding: utf-8 -*-
"""Trascrever_Audio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srRzq-Aasdhxe8LsKgYhp4jftenguyct
"""

!pip install openai-whisper

from google.colab import files

uploaded = files.upload()

import whisper
from google.colab import files
import os

# Carrega o modelo Whisper (pode ser "tiny", "base", "small", "medium" ou "large")
model = whisper.load_model("small")

# Confirma que arquivos foram carregados
if not uploaded:
    print("Nenhum arquivo carregado. Faça o upload primeiro.")
else:
    for filename in uploaded.keys():
        try:
            print(f"\n➡️ Transcrevendo: {filename} ...")

            # Faz a transcrição em português
            result = model.transcribe(filename, language="pt")

            # Cria o nome do arquivo de saída
            txt_filename = os.path.splitext(filename)[0] + ".txt"

            # Salva a transcrição em arquivo .txt
            with open(txt_filename, "w", encoding="utf-8") as f:
                f.write(result["text"])

            print(f"✅ Transcrição salva: {txt_filename}")

        except Exception as e:
            print(f"❌ Erro ao transcrever {filename}: {e}")

for filename in uploaded.keys():
    txt_filename = filename.rsplit(".", 1)[0] + ".txt"
    files.download(txt_filename)